branch-defaults:
  master:
    environment: jeffchenseo-dev
    group_suffix: null
environment-defaults:
  jeffchenseo-dev:
    branch: null
    repository: null
global:
  application_name: jeffchenseo
  branch: null
  default_ec2_keyname: jeffchenseo-aws-eb
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli3
  repository: null
  sc: git
  workspace_type: Application
