# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_profile_dt_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
