# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_auto_20171015_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
    ]
